name: Coverage
on:
    pull_request:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        with:
            package-manager: yarn
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
